version: 2.1

orbs:
  python: circleci/python@1.3.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9  # or whichever version you prefer
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            # If you have dependencies, install them here
            # e.g.: pip install -r requirements.txt
            echo "No external dependencies for now"
      - run:
          name: Run Python unittests
          command: |
            python -m unittest -v test_unittest.py

workflows:
  build_and_test_workflow:
    jobs:
      - build-and-test
